# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='num_cupos',
            new_name='numEstudiantes',
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='numcupos',
            field=models.CharField(default=datetime.datetime(2016, 7, 19, 13, 38, 59, 944941, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
