# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20160719_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='numEstudiantes',
        ),
        migrations.AddField(
            model_name='materia',
            name='num_Estudiantes',
            field=models.CharField(default=datetime.datetime(2016, 7, 19, 13, 39, 35, 921217, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
